In [9]:
import numpy as np

def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

y = np.array([[0],
             [1],
             [1],
             [0]])

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in xrange(60000):
    k0 = x
    k1 = nonlin(np.dot(k0,syn0))
    k2 = nonlin(np.dot(k1,syn1))
    
    k2_error = y - k2
    
    if(j % 10000) == 0:
        print("Error:"+str(np.mean(np.abs(k2_error))))
        
    k2_delta = k2_error*nonlin(k2,deriv=True)
    
    k1_error = k2_delta.dot(syn1.T)
    
    k1_delta = k1_error*nonlin(k1,deriv=True)
    
    syn1 += k1.T.dot(k2_delta)
    syn0 += k0.T.dot(k1_delta)

Error:0.496410031903
Error:0.00858452565325
Error:0.00578945986251
Error:0.00462917677677
Error:0.00395876528027
Error:0.00351012256786


In [5]:
print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [6]:
print y

[[0]
 [1]
 [1]
 [0]]


In [7]:
print syn0

[[ 4.6013571   4.17197193 -6.30956245 -4.19745118]
 [-2.58413484 -5.81447929 -6.60793435 -3.68396123]
 [ 0.97538679 -2.02685775  2.52949751  5.84371739]]


In [8]:
print syn1

[[ -6.96765763]
 [  7.14101949]
 [-10.31917382]
 [  7.86128405]]
